name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # 원하는 Node.js 버전으로 변경 가능

      - name: Install dependencies
        run: yarn run install

      - name: Run tests
        run: yarn run test:ci

      - name: Build
        run: yarn run build
