name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn run install

      - name: Run tests
        run: yarn run test:ci

      - name: Build
        run: yarn run build

      - name: Read version from package.json
        id: get_version
        run: echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ap-northeast-2

      - name: Build and tag the Docker image
        run: |
          # AWS 계정 ID와 ECR URL 설정
          ECR_REGISTRY=639578488701.dkr.ecr.ap-northeast-2.amazonaws.com
          ECR_REPOSITORY=no-support/greeny

          # package.json의 version 값 가져오기
          IMAGE_TAG=${{ env.VERSION }}

          # Docker 이미지를 latest와 버전 태그로 빌드
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

      - name: Push the Docker image to ECR
        run: |
          ECR_REGISTRY=639578488701.dkr.ecr.ap-northeast-2.amazonaws.com
          ECR_REPOSITORY=no-support/greeny

          # 이미지를 latest와 버전 태그로 푸시
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.VERSION }}
