FROM --platform=linux/amd64 node:18.17.0-alpine3.18

ENV PORT=80
ARG NEXT_PUBLIC_API_SERVER
ARG NEXT_PUBLIC_LIMIT
ARG NEXT_PUBLIC_DB_NAME
ARG GITHUB_CLIENT_ID
ARG GITHUB_CLIENT_SECRET
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG DB_SERVER
ARG OPEN_API_KEY
ARG NEXT_PUBLIC_KAKAO_API_KEY
ARG AUTH_SECRET

ENV NEXT_PUBLIC_API_SERVER=${NEXT_PUBLIC_API_SERVER}
ENV NEXT_PUBLIC_LIMIT=${NEXT_PUBLIC_LIMIT}
ENV NEXT_PUBLIC_DB_NAME=${NEXT_PUBLIC_DB_NAME}
ENV GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
ENV GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
ENV GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
ENV GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
ENV DB_SERVER=${DB_SERVER}
ENV OPEN_API_KEY=${OPEN_API_KEY}
ENV NEXT_PUBLIC_KAKAO_API_KEY=${NEXT_PUBLIC_KAKAO_API_KEY}
ENV AUTH_SECRET=${AUTH_SECRET}
ENV REACT_EDITOR=atom

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Copy build output files
COPY node_modules node_modules
COPY package.json package.json
COPY public public
COPY .next .next
COPY next.config.mjs next.config.mjs

EXPOSE $PORT

# Running the app
ENTRYPOINT [ "yarn", "start" ]